### ISSUE TITLE
unknown units

### ISSUE THREAD

**Issue by ckolbPTB** [ckolbPTB/InhomCorr#15]
So far we have not specified the unites of e.g. t1 anywhere. We could 

1. add this in the comments of QMRIData 
2. change "t1" to "t1_in_s"

I would prefer option 2. What do you think?

**Comment by fzimmermann89** [comment]
agree, slight preference for option 2.
would we have rho_in_au? or rho? or does it have a proper unit?

**Comment by schuenke** [comment]
I don't really like the idea of changing the public name to be honest. I think a good documentation is enough, but ofc I can live with both solutions :D

**Comment by fzimmermann89** [comment]
The questions is, do we prefer to have
`Image = ... exp(-t_in_s/t1_in_s)`
or `Image=... exp(-t_in_s/t1_in_s)`

It might be nice to name most variables with the units, just to make sure there are no mistakes and conversions are clear, i.e. db0_hz vs db0_ppm.
If we add the units, I would prefer to have them everywhere, i.e. also the other parameters of a signal model and even inside the functions (see above).

Or we decide this is too much clutter and only put it in the comments / docstrings.

**Comment by schuenke** [comment]
We decided to:

- always use SI units and mention it in the documentation
- keep the attribute names without units, but mention the units in all docstrings
- in our code, add some comments about units where it might be useful (e.g. if dB0 is in Hz or ppm)
